### ISSUE TITLE
Label anchor position

### ISSUE THREAD

**Issue by dumbeau** [ryjacky/PieMenyu#1]
This one is a simple one that I realized waaay later than I should've.

Currently, the anchor position for the location of the label is placed on the edge of the label:
![image](https://github.com/ryjacky/PieMenyu/assets/36665762/c69e767e-7506-4a5b-a6a8-f7f80142d5ce)

The anchor position should be offset inwards by 'half of the height' of the label
![image](https://github.com/ryjacky/PieMenyu/assets/36665762/41bd242f-deeb-4f38-a0a6-e13ea6be9abc)

The reason for this is that when the labels have only a square icon inside of the label, the center of the label will sit directly in the motion path for that slice.

**Comment by ryjacky** [comment]
will be added in the next alpha version 0.0.2-alpha #2
