### ISSUE TITLE
Escape radius doesn`t work...?

### ISSUE THREAD

**Issue by chenpaner** [ryjacky/PieMenyu#24]
1. I set the Escape radius but it doesn`t seem to work

2. What is the setting of Icon color? Why don’t I see any changes after setting it? Is it set for a function that has not been released yet?

**Comment by ryjacky** [comment]
1. Escape radius should've worked at some point but it seems likely the code is removed accidentally or I never committed it.
2. This is actually a feature that I've forgotten about, the icon upload should allow selecting a predefined set of icons according to the initial plan, which the color of these icons can be changed dynamically, but yeah, the feature isn't there yet
